name: Workflow dotnet build I

on:
  # push:
  #   branches:
  #     - main
  #     - develop
  workflow_dispatch:
    inputs:
      dotnetversion:
        description: 'Version to build'
        required: false
        default: '8.0.x'
      artifactname:
        description: 'Artifact name'
        required: false
        default: 'app-package'  

permissions:
  id-token: write
  contents: write

env:
  BUILD_CONFIGURATION: 'Release'

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.extract_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Version from changelog
        id: extract_version
        run: |
          VERSION=$(grep -oPm1 "(?<=## \[)[^]]+" CHANGELOG.md)
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  build:
    runs-on: windows-latest
    needs: extract-version
    steps:
      - name: Muestra version
        run: echo "version en ${{ needs.extract_version.outputs.app_version }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ github.event.inputs.dotnetversion }}

      - name: Restore
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION}} 

      - name: publish
        run: dotnet publish --no-build --configuration ${{ env.BUILD_CONFIGURATION}}  --output ./publish

      - name: Zip artifact
        run: Compress-Archive -Path ./publish/* -DestinationPath ./${{ github.event.inputs.artifactname }}.zip
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.artifactname }}
          path: ${{ github.event.inputs.artifactname }}.zip
          retention-days: 5      

  deploy:  
    runs-on: ubuntu-latest
    needs: build
    environment: develop
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.artifactname }}
      - name: Mostrar varable
        run: echo "Variable a mostrar en ${{ vars.VARIABLE_GITHUB }}"
    
